server:
  port: 9100

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB
  datasource:
    driver-class-name: ${rollcallsystem.datasource.driver-class-name}
    url: jdbc:mysql://${rollcallsystem.datasource.host}:${rollcallsystem.datasource.port}/${rollcallsystem.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${rollcallsystem.datasource.username}
    password: ${rollcallsystem.datasource.password}
  # redis:
  #   host: ${sky.redis.host}
  #   port: ${sky.redis.port}
  #   database: ${sky.redis.database}
  #   timeout: 5000             # Redis 鐨勮繛鎺ヨ秴鏃舵椂闂达紝鍗曚綅姣

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: '鍏ㄩ儴鎺ュ彛'
      paths-to-match: '/**'
      packages-to-scan: com.project.backend.controller

knife4j:
  enable: false
  setting:
    language: zh_cn

mybatis:
  #mapper閰嶇疆鏂囦欢
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.project.backend.pojo.entity
  configuration:
    #寮€鍚┘宄板懡鍚?
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      rollcallsystem:
        mapper: debug
        service: info
        controller: info

rollcallsystem:
  jwt:
    # 璁剧疆jwt绛惧悕鍔犲瘑鏃朵娇鐢ㄧ殑绉橀挜
    admin-secret-key: RollCallSystemJasminum-2026-2-10
    # 璁剧疆jwt杩囨湡鏃堕棿
    admin-ttl: 86400000
    # 璁剧疆鍓嶇浼犻€掕繃鏉ョ殑浠ょ墝鍚嶇О
    admin-token-name: token
  minio:
    endpoint: ${rollcallsystem.minio.endpoint}
    access-key: ${rollcallsystem.minio.access-key}
    secret-key: ${rollcallsystem.minio.secret-key}
    bucket-name: ${rollcallsystem.minio.bucket-name}
  python-service:
    # Python 绠楁硶鏈嶅姟鍦板潃
    base-url: ${rollcallsystem.python-service.url}
